<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: liuchao
 * Date: Fri, 22 Jan 2016 22:02:53 +0800
 */

$conf['title'] = '维勒个基';
$conf['lang'] = 'zh';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['proxy']['user'] = 'thesedays@126.com';
$conf['proxy']['pass'] = '<b>bml2ZWE0TUVO';

// end auto-generated content
